/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.tutorial;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LoxTest {
    @Test void appHasAGreeting() {
        Lox classUnderTest = new Lox();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
